import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans_Flex } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "./providers";
import { Header } from "@/shared/components/Header";
import { Footer } from "@/shared/components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
});

const sebangGothic = localFont({
  src: "./fonts/SebangGothic-Bold.woff2",
  variable: "--font-sebang-gothic",
  weight: "700",
});

const kyoboHandwriting = localFont({
  src: "./fonts/KyoboHandwriting2025.woff2",
  variable: "--font-kyobo-handwriting",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${googleSansFlex.variable} ${sebangGothic.variable} ${kyoboHandwriting.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
